#!/bin/bash

MINECRAFT_RUN_DIR=
MINECRAFT_RUN_MEM=1024m
MINECRAFT_RUN_WORLD=world
MINECRAFT_RUN_USER=

MINECRAFT_BACKUP_DIR=
MINECRAFT_BACKUP_MAXAGE_DAYS=7

MINECRAFT_MAP_DIR=

# mapping tools
# MINECRAFT_MAP_FUNC=c10t-run
# MINECRAFT_MAP_FUNC=minecraftoverviewer-run

MINECRAFT_MAP_C10TDIR=
MINECRAFT_MAP_MINECRAFTOVERVIEWERDIR=

